### ISSUE TITLE
Update privacy document

### ISSUE THREAD

**Issue by maarten0912** [Inter-Actief/Amelie-GDPR-document#12]
The privacy document has not been updated in a while, and requires changes. Firstly, Inter-Actief uses Exact for financial bookkeeping, which should be incorporated into the document. Furthermore, the document should be checked for things that are outdated and not used anymore. Lastly, it might be worthwhile to look into how preferences of members are written in the document.

**Comment by Kurocon** [comment]
Fixed in #13
